version: '3.7'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env.prod
    user: '501:501'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: arosaje
      POSTGRES_PASSWORD: arosaje
      POSTGRES_DB: arosaje
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
