export const plant = [
    {
      name: "Rose",
      species: { connect: { id: 1 } },
      status: { connect: { id: 1 } },
      address: { connect: { id: 1 } },
      user: { connect: { id: 1 } },
    },
    {
      name: "Tulipe",
      species: { connect: { id: 4 } },
      status: { connect: { id: 1 } },
      address: { connect: { id: 5 } },
      user: { connect: { id: 1 } },
    },
    {
      name: "Tournesol",
      species: { connect: { id: 6 } },
      status: { connect: { id: 1 } },
      address: { connect: { id: 7 } },
      user: { connect: { id: 3 } },
    },
    {
      name: "Marguerite",
      species: { connect: { id: 8 } },
      status: { connect: { id: 3 } },
      address: { connect: { id: 9 } },
      user: { connect: { id: 1 } },
    },
    {
      name: "Lys",
      species: { connect: { id: 10 } },
      status: { connect: { id: 4 } },
      address: { connect: { id: 10 } },
      user: { connect: { id: 4 } },
    },
    {
      name: "Orchidée",
      species: { connect: { id: 12 } },
      status: { connect: { id: 5 } },
      address: { connect: { id: 4 } },
      user: { connect: { id: 1 } },
    },
    {
      name: "Lavande",
      species: { connect: { id: 14 } },
      status: { connect: { id: 6 } },
      address: { connect: { id: 5 } },
      user: { connect: { id: 1 } },
    },
    {
      name: "Souci",
      species: { connect: { id: 16 } },
      status: { connect: { id: 7 } },
      address: { connect: { id: 7 } },
      user: { connect: { id: 4 } },
    },
    {
      name: "Pivoine",
      species: { connect: { id: 18 } },
      status: { connect: { id: 8 } },
      address: { connect: { id: 8 } },
      user: { connect: { id: 4 } },
    },
    {
      name: "Chrysanthème",
      species: { connect: { id: 20 } },
      status: { connect: { id: 7 } },
      address: { connect: { id: 9 } },
      user: { connect: { id: 1 } },
    },
];
