export const plantSpecies = [
  { name: 'Chêne' },
  { name: 'Érable' },
  { name: 'Bouleau' },
  { name: 'Sapin' },
  { name: 'Pin' },
  { name: 'Hêtre' },
  { name: 'Frêne' },
  { name: 'Orme' },
  { name: 'Tilleul' },
  { name: 'Châtaignier' },
  { name: 'Magnolia' },
  { name: 'Camélia' },
  { name: 'Azalée' },
  { name: 'Hortensia' },
  { name: 'Rhododendron' },
  { name: 'Rose' },
  { name: 'Tulipe' },
  { name: 'Jonquille' },
  { name: 'Lys' },
  { name: 'Gerbera' },
];
