name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: mspr

    steps:
    - uses: actions/checkout@v4

    - name: Extract version
      id: extract_version
      run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
  
    - name: Build Docker image
      run: docker build -t ${{ secrets.DH_USERNAME }}/${{ vars.DH_REPOSITORY }}:${{ steps.extract_version.outputs.VERSION }} .

    - name: Tag Docker image as latest
      run: docker tag ${{ secrets.DH_USERNAME }}/${{ vars.DH_REPOSITORY }}:${{ steps.extract_version.outputs.VERSION }} ${{ secrets.DH_USERNAME }}/${{ vars.DH_REPOSITORY }}:latest

    - name: Log in to Docker Hub Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}

    - name: Push Docker image with version tag
      run: docker push ${{ secrets.DH_USERNAME }}/${{ vars.DH_REPOSITORY }}:${{ steps.extract_version.outputs.VERSION }}

    - name: Push Docker image with latest tag
      run: docker push ${{ secrets.DH_USERNAME }}/${{ vars.DH_REPOSITORY }}:latest
