name: Run Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm ci

      - name: Copy environment file
        run: cp .env.dist .env

      - name: Reset Prisma
        run: npm run prisma:reset

      - name: Run tests
        run: npm test
